---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
