---
apiVersion: v1
kind: Service
metadata:
  name: mikrotik-exporter
  namespace: monitoring
spec:
  selector: 
    app: mikrotik-exporter
  type: NodePort  
  ports:
    - port: 9436
      targetPort: 9436
