---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsNonRoot: true
        runAsUser: 472
      containers:
      - name: grafana
        image: grafana/grafana:7.3.7
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
          - name: grafana-ini
            mountPath: /etc/grafana/
          - name: grafana-certs
            mountPath: /etc/grafana/certs/
            readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: nfs-pvc-grafana
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-ini
          configMap:
            name: grafana-ini
        - name: grafana-certs
          secret:
            secretName: grafana-tls-cert
            items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
